### ISSUE TITLE
Create bundle from certificate and intermediate chain

### ISSUE THREAD

**Issue by manics** [openmicroscopy/ansible-role-ssl-certificate#3]
This role currently assumes the certificate file contains the intermediate chain. Instead this role should take three inputs:
- certificate
- key
- intermediate chain

and create a bundled certificate if required.

**Comment by sbesson** [comment]
Is this effectively implemented in https://github.com/openmicroscopy/ansible-role-ssl-certificate/pull/1/commits/227b2b2b898af033a3a0588742d67f17e643b4b9 ?
