### ISSUE TITLE
Check parameters task fails with vault-encrypted variables

### ISSUE THREAD

**Issue by dweingart** [openmicroscopy/ansible-role-ssl-certificate#6]
The length filter doesn't work on variables encrypted with Vault due to Ansible bug [24425](https://github.com/ansible/ansible/issues/24425).

Because the empty string evaluates to false you can change the logic to this, which works with encrypted variables.

```yaml
when: >-
    (not ssl_certificate_selfsigned_create) and
    (not ssl_certificate_public_content or not ssl_certificate_key_content)
```

**Comment by sbesson** [comment]
@dweingart thanks for reporting this issue and suggesting the fix which is now included in version 0.2.1 of [https://galaxy.ansible.com/openmicroscopy/ssl-certificate/](openmicroscopy.ssl-certificate).
