### ISSUE TITLE
Newline char stripped from EOF on deployed files

### ISSUE THREAD

**Issue by kennethgillen** [openmicroscopy/ansible-role-ssl-certificate#9]
There's an Ansible bug in `lookup` which means files deployed using this mechanism have `rtrim` applied, and so are missing the Newline char `0x0a` 

Ref: https://github.com/ansible/ansible/issues/30829

```
2018-10-09 09:52 LS27172:~ kenny$ diff -y -W 190 <(hexdump -C from-ansible-role-ssl-certificate.crt) <(hexdump -C from-original-file.crt)  | tail -n 3
00001a00  2d 45 4e 44 20 43 45 52  54 49 46 49 43 41 54 45  |-END CERTIFICATE|                  00001a00  2d 45 4e 44 20 43 45 52  54 49 46 49 43 41 54 45  |-END CERTIFICATE|
00001a10  2d 2d 2d 2d 2d                                    |-----|                           | 00001a10  2d 2d 2d 2d 2d 0a                                 |-----.|
00001a15                                                                                      | 00001a16
2018-10-09 09:52 LS27172:~ kenny$
```

**Comment by manics** [comment]
Does this break anything?

**Comment by kennethgillen** [comment]
It breaks consistency, directly.  The files on disk end up with the wrong checksum. 

Indirectly, there are tools and applications which have undefined behaviours with files which end with no Newline, so it's very much recommended to avoid.

I have a fix, and primarily opened this Issue to then open the fix PR.

**Comment by kennethgillen** [comment]
Since `lookup` is applied outside this role, it's not just an issue for this role, other than in the README.
